config/routes.rb
Rails.application.routes.draw do
  


      # 管理者用
      # URL /admin/sign_in ...
    devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
      sessions: "admin/sessions"
    }

    namespace :admin do
      root to: "homes#home"

      resources :customers
      resources :items

        
        # 確認画面作成中断
          # collection do
          #   post "confirm"
          #   # patch 'edit_confirm'
          # end
      resources :tags
      resources :contacts
      resources :orders
    end


      # 顧客用
      # URL /customers/sign_in ...
    devise_for :customers,skip: [:passwords], controllers: {
      registrations: "public/registrations",
      sessions: 'public/sessions'
    } 


    scope module: :public do
      root to: 'homes#top'
      get "home", to: "homes#home"
      
      resources :items, only: [:index, :show]
      resources :customers, only: [:show, :edit, :update] do
        get '/customers/:id/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
        # 論理削除
        patch '/customers/:id/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
      end

        resources :contacts, only: [:index,:show,:create,:destroy]
        resources :cart_items, only:[:index,:show,:update,:create,:destroy]
          delete '/cart_items' => 'cart_items#destroy_all'
          post '/orders/comfirm' => 'orders#comfirm'
          get '/orders/complete' => 'orders#complete'
        
        resources :orders
        resources :order_details
        

      
    end





end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def home
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/views/admin/homes/home.html.erb
<div class="container-fluid">

  <div class="text-center my-5">
    <h2>管理者ホーム</h2>
  </div>
  <div class="row justify-content-center border text-center">


    <div class="col-sm-3 py-3 border">
      <h3>
        <%= link_to "注文一覧", admin_orders_path %>
      </h3>
    </div>

    <div class="col-sm-3 py-3 border">
      <h3>
        <%= link_to "商品一覧", admin_items_path %>
      </h3>
    </div>

    
   
    
    <div class="w-100">
    </div>

    <div class="col-sm-3 py-3 border">
      <h3>
        <%= link_to "会員一覧", admin_customers_path %>
      </h3>
    </div>


    <div class="col-sm-3 py-3 border">
      <h3>
        <%= link_to "タグ一覧", admin_tags_path %>
      </h3>
    </div>


    <div class="w-100">
    </div>

    <div class="col-sm-3 py-3 border">
      <h3>
        <%= link_to "お問い合わせ一覧", admin_contacts_path %>
      </h3>
    </div>

  </div>
</div>