config/routes.rb
Rails.application.routes.draw do
  


      # 管理者用
      # URL /admin/sign_in ...
    devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
      sessions: "admin/sessions"
    }

    namespace :admin do
      root to: "homes#home"

      resources :customers
      resources :items

        
        # 確認画面作成中断
          # collection do
          #   post "confirm"
          #   # patch 'edit_confirm'
          # end
      resources :tags
      resources :contacts
      resources :orders
    end


      # 顧客用
      # URL /customers/sign_in ...
    devise_for :customers,skip: [:passwords], controllers: {
      registrations: "public/registrations",
      sessions: 'public/sessions'
    } 


    scope module: :public do
      root to: 'homes#top'
      get "home", to: "homes#home"
      
      resources :items, only: [:index, :show]
      resources :customers, only: [:show, :edit, :update] do
        get '/customers/:id/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
        # 論理削除
        patch '/customers/:id/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
      end

        resources :contacts, only: [:index,:show,:create,:destroy]
        resources :cart_items, only:[:index,:show,:update,:create,:destroy]
          delete '/cart_items' => 'cart_items#destroy_all'
          post '/orders/comfirm' => 'orders#comfirm'
          get '/orders/complete' => 'orders#complete'
        
        resources :orders
        resources :order_details
        

      
    end





end

app/models/tag.rb
class Tag < ApplicationRecord

  #　<%= "(#{tags.items.count})" %>を記述すると、エラーになる。上下入れ替えたら治った。

  has_many :item_tags, dependent: :destroy
  has_many :items, through: :item_tags

  

  validates :tag_name, presence: true

end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
  def index
    @tag = Tag.new
    @tags = Tag.order(tag_name: :asc)
  end

  def create
    # 半角スペースで区切る
    tags = tag_params[:tag_name].split(" ")

    # 同じ値が存在したら取得し、無ければ作成 (カラム名: ブロック変数)
    tags.each do |tag|
      Tag.find_or_create_by(tag_name: tag)
    end
    redirect_to admin_tags_path
    flash[:notice] = "タグを追加しました"
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def update
    @tag = Tag.find(params[:id])
    if @tag.update(tag_params)
      redirect_to admin_tags_path
      flash[:notice] = "タグを更新しました"
    else
      @tag = Tag.find(params[:id])
      render "edit"
      flash[:alert] = "タグを更新できませんでした"
    end
  end

  def destroy
    @tag = Tag.find(params[:id])
    if @tag.destroy
      redirect_to admin_tags_path
      flash["notice"] = "タグを削除しました"
    else
      @tag = Tag.find(params[:id])
      flash["alert"] = "タグを削除できませんでした"
    end
    
  end

  private

  def tag_params
    params.require(:tag).permit(:tag_name)
  end


end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/views/admin/tags/edit.html.erb
<div class="container-fluid">

  <div class="text-center my-5">
    <p class="admin-nav"><%= link_to "管理者ホーム", admin_root_path %> | <%= link_to "タグ一覧に戻る", admin_tags_path %></p>
  </div>

  
  <div class="text-center my-5">
    <h2>タグ編集</h2>
  </div>

  <%= form_with model: @tag, url: admin_tag_path ,method: :patch do |f| %>
      <div class="text-center"><small class="note-text">複数のタグは登録できません</small></div>
      <div class="row justify-content-center">
        <div class="col col-md-4 my-3">
          <%= f.text_field :tag_name, class:"form-control" %>
        </div>
        <div class="col-md-1 my-3 text-center">
          <%= f.submit "更新", class:"btn btn-primary" %>
        </div>  
      </div>
  <% end %>
</div>

app/views/admin/tags/index.html.erb
<div class="container-fluid">

  <%= render "admin/shared/admin_nav" %>

  <div class="text-center my-5">
    <h2>タグの追加と一覧</h2>
  </div>

  <div class="col text-center">
    <small class="note-text">半角スペースで区切ると、複数のタグを追加できます</small>
  </div>

  <%= form_with model: @tag, url: admin_tags_path do |f| %>
    <div class="row justify-content-center">
      <div class="col-md-4 my-3">
          <%= f.text_field :tag_name, class: "form-control" %>
      </div>
      <div class="col col-md-1 text-center my-3">
          <%= f.submit "追加", class: "btn btn-success" %>
      </div>
    </div>
  <% end %>


    <div class="text-center my-4">
       <h2>タグ一覧</h2>
    </div>
    <div class="text-center">
      <small class="note-text">タグをクリックすると編集できます</small>
    </div>

  <div class="row mt-3 justify-content-center">
    <div class="col col-md-8">
      <% @tags.each do |tags| %>  
      <span class="div-tag">
          <span class="orign-tag">
            <%= link_to edit_admin_tag_path(tags.id),class:"no-underline" do %>
              <span class="py-1 px-1"><%= tags.tag_name %></span>
            <% end %>
          </span>
          <span class="delete-tag" >
            <%= link_to admin_tag_path(tags.id), method: :delete, data:{confirm: "「#{tags.tag_name}」を削除しますか？"} do %>
              <span class="py-1 px-1">X</span>
            <% end %>
          </span>
          <span class="tag-count">
            <%= "(#{tags.items.count})" %>
          </span>
      </span>
      <% end %>
    </div>      
  </div>
</div>