config/routes.rb
Rails.application.routes.draw do
  


      # 管理者用
      # URL /admin/sign_in ...
    devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
      sessions: "admin/sessions"
    }

    namespace :admin do
      root to: "homes#home"

      resources :customers
      resources :items

        
        # 確認画面作成中断
          # collection do
          #   post "confirm"
          #   # patch 'edit_confirm'
          # end
      resources :tags
      resources :contacts
      resources :orders
    end


      # 顧客用
      # URL /customers/sign_in ...
    devise_for :customers,skip: [:passwords], controllers: {
      registrations: "public/registrations",
      sessions: 'public/sessions'
    } 


    scope module: :public do
      root to: 'homes#top'
      get "home", to: "homes#home"
      
      resources :items, only: [:index, :show]
      resources :customers, only: [:show, :edit, :update] do
        get '/customers/:id/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
        # 論理削除
        patch '/customers/:id/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
      end

        resources :contacts, only: [:index,:show,:create,:destroy]
        resources :cart_items, only:[:index,:show,:update,:create,:destroy]
          delete '/cart_items' => 'cart_items#destroy_all'
          post '/orders/comfirm' => 'orders#comfirm'
          get '/orders/complete' => 'orders#complete'
        
        resources :orders
        resources :order_details
        

      
    end





end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :item
  belongs_to :customer

  validates :item_id, :item_quantity, presence: true

       #小計金額
       def small_total_price
        (item.on_tax_price * item_quantity).floor
      end


end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
    devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable


    has_many :orders, dependent: :destroy
    has_many :cart_items, dependent: :destroy
    has_many :addresses, dependent: :destroy


    validates :last_name,  presence: true
    validates :first_name, presence: true
    validates :last_name_kana, presence: true
    validates :first_name_kana, presence: true
    validates :birth, presence: true
    validates :postcode, presence: true
    validates :prefecture_code, presence: true
    validates :address_city, presence: true
    validates :address_street, presence: true
    validates :tel_number, presence: true

    
  def customer_name
    last_name + " " + first_name
  end

  def customer_name_kana
    last_name_kana + " " + first_name_kana
  end



  # jpostal.jsで使うメソッド。郵便番号を入力で、住所自動入力
  include JpPrefecture
  jp_prefecture :prefecture_code
  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end
  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end


    #is_deletedがfalseなら、有効。trueなら退会
  def active_for_authentication?
    super && (is_deleted == false)
  end


  # 個別の住所をまとめて表示させる。
  def join_address
    "#{self.prefecture_name}#{self.address_city}#{self.address_street}"
  end

  #生年月日から、年齢を計算する
  def age
    dob = self.birth # birth カラムの値を取得
    now = Time.current.to_date
    age = now.year - dob.year - (now.strftime("%m%d") < dob.strftime("%m%d") ? 1 : 0)
    return age
  end
  # strftime = rubyのメソッド。日付や時刻を指定されたフォーマットで文字列に変換する。
  # 例: now.strftime("%y/%m/%d")
  # メソッドの最後に return を書くことで、その時点での値を返してメソッドを終了


end

app/models/item.rb
class Item < ApplicationRecord

  has_one_attached :image

  has_many :item_tags, dependent: :destroy
  has_many :tags, through: :item_tags
  has_many :cart_items, dependent: :destroy
  

  validates :item_name,:item_text,:no_tax_price,:stock,:sale_status, presence: true
  

  # 画像を取り扱う。
  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no-images.png')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  # 編集するとき、タグの入れ替えをする。
  def save_tag(sent_tags)
    unless sent_tags.empty?
      self.item_tags.destroy_all

      sent_tags.each do |new|
        new_post_tag = Tag.find_or_create_by(tag_name: new)

        unless self.tags.include?(new_post_tag)
          #include? => アイテムにすでに同じタグが関連付けられているかどうかをチェックし、
          #それがない場合にのみ、新しいタグをアイテムに関連付けする
          
          self.tags << new_post_tag
           #<<演算子 新しいタグがアイテムに関連付けられ、データベースに保存される。
        end
      end
    end
  end

  # 消費税込みの値段
  def on_tax_price
    tax_rate = 1.1
  (self.no_tax_price * tax_rate).floor
  end

  enum sale_status: {onSale: 0, stopSale: 1, backOrdered: 2, soldOut: 3}

  # 在庫が0になったら、売り切れに更新
  def out_of_stock
    if self.stock <= 0
      self.update(sale_status: "soldOut")
    end
  end


end

app/models/item_tag.rb
class ItemTag < ApplicationRecord

  belongs_to :tag
  belongs_to :item

end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/oreder_detail.rb
class OrederDetail < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord

  #　<%= "(#{tags.items.count})" %>を記述すると、エラーになる。上下入れ替えたら治った。

  has_many :item_tags, dependent: :destroy
  has_many :items, through: :item_tags

  

  validates :tag_name, presence: true

end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
  def index
    @tag = Tag.new
    @tags = Tag.order(tag_name: :asc)
  end

  def create
    # 半角スペースで区切る
    tags = tag_params[:tag_name].split(" ")

    # 同じ値が存在したら取得し、無ければ作成 (カラム名: ブロック変数)
    tags.each do |tag|
      Tag.find_or_create_by(tag_name: tag)
    end
    redirect_to admin_tags_path
    flash[:notice] = "タグを追加しました"
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def update
    @tag = Tag.find(params[:id])
    if @tag.update(tag_params)
      redirect_to admin_tags_path
      flash[:notice] = "タグを更新しました"
    else
      @tag = Tag.find(params[:id])
      render "edit"
      flash[:alert] = "タグを更新できませんでした"
    end
  end

  def destroy
    @tag = Tag.find(params[:id])
    if @tag.destroy
      redirect_to admin_tags_path
      flash["notice"] = "タグを削除しました"
    else
      @tag = Tag.find(params[:id])
      flash["alert"] = "タグを削除できませんでした"
    end
    
  end

  private

  def tag_params
    params.require(:tag).permit(:tag_name)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  # before_action :authenticate_admin!, if: :admin_url



     #URLにadminが含まれているかの確認
    def admin_url
      request.fullpath.include?("/admin")
    end


    def after_sign_in_path_for(resource_or_scope)
      if resource_or_scope.is_a?(Admin)
        admin_root_path
      else
        items_path
      end
    end

    def after_signin_out_path_for(resource_or_scope)
      if resource_or_scope == :customer
        root_path
      elsif resource_or_scope == :admin
        new_admin_session_path
      else
        root_path
      end
    end




  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [
      :last_name,
      :first_name,
      :last_name_kana,
      :first_name_kana,
      :birth,
      :postcode,
      :prefecture_code,
      :address_city,
      :address_street,
      :address_other,
      :tel_number

    ])
  end

end

app/helpers/admin/contacts_helper.rb
module Admin::ContactsHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_admin_nav.html.erb
<div class="text-center my-5">
   <!-- items/index -->
  <% if current_page?(admin_items_path) || current_page?(admin_customers_path) %>
    <p class="admin-nav"><%= link_to "管理者ホーム", admin_root_path %> | <%= link_to "商品追加", new_admin_item_path %> | <%= link_to "タグ追加", admin_tags_path %></p>
  <% end %>
  
  <!-- items/new -->
  <% if current_page?(new_admin_item_path) || current_page?(admin_tags_path) %>
   <p class="admin-nav"><%= link_to "管理者ホーム", admin_root_path %> | <%= link_to "商品一覧", admin_items_path %></p>
  <% end %>


</div>

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/admin/shared/_menu.html.erb
  <div id="position-right">
    <%= link_to admin_items_path do %>
      <div class="right-menu">商品一覧</div>
    <% end %>
    <a class="button-link"><div id="modal-open" class="right-menu">タグ検索</div></a>
    <a href=""><div id="top-upper" class="right-menu">TOPへ</div></a>
  </div>

    <!--タグ一覧はモーダルウィンドウで表示する-->
  <div id="modal-tag">
    <p id="modal-close"><a class="button-link py-3">閉じる</a></p>
  

    <div class="col">
      <% tag_list.each do |tag_list| %>
        <span class="div-tag">
          <span class="nomal-tag">
            <%= link_to tag_list.tag_name, admin_items_path(tag_id: tag_list.id) %>
          </span>
          <span class="tag-count">
            <%= "(#{tag_list.items.count})" %>
          </span>
        </span>
      <% end %>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>MidnightBar</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script type="text/javascript" src="//jpostal-1006.appspot.com/jquery.jpostal.js"></script>

  </head>

  <body>


    <!--バニーガールの画像をクリックすると、ナビが出てくる。TOPページにはでないようにしたい-->
    <% unless admin_signed_in? || current_page?(root_path) %>
    <div class="toggle-menu">
      <%= image_tag "menu_bunnygirl.gif", size:"120x120" %>
    </div>
    <nav class="menu">

      <% if customer_signed_in? %>
        <div><%= link_to "会員証を見る(マイページ)",current_customer %></div>
        <div><%= link_to "注文票を見る(カート内)",cart_items_path %></div>
        <div><%= link_to "サインアウト", destroy_customer_session_path,method: :delete %></div>

      <% else %>
        <div><%= link_to "会員登録したい(新規登録)", new_customer_registration_path %></div>
        <div><%= link_to "サインイン", new_customer_session_path %></div>
      <% end %>
        <div><%= link_to "商品を見せて(商品一覧)" %></div>
        <div><%= link_to "店から出る(TOP)", root_path %></div>
    </nav>
    <% end %>



    <div class="col text-center alert-danger">
      <%= flash[:notice] %>
    </div>
    
    

    <%= yield %>
    
    <header>
      <div class="text-center my-5">
        <small>&copy; 2023 kamishubaizumo</small>
      </div>
    </header>
  </body>
</html>